version: '3.8'
services:

  db:
    container_name: db-blog
    image: mysql
    restart: always
    volumes:
     - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Crocante@1316
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: Crocante@1316
    ports:
      - "3306:3306"
 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8282:8080